//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoActions.ProjectResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectLocales {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectLocales() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoActions.ProjectResources.ProjectLocales", typeof(ProjectLocales).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Set HDR ähnelt.
        /// </summary>
        public static string Action_HDRSwitch {
            get {
                return ResourceManager.GetString("Action_HDRSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HDR ähnelt.
        /// </summary>
        public static string ActionGroup_HDR {
            get {
                return ResourceManager.GetString("ActionGroup_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action shortcuts ähnelt.
        /// </summary>
        public static string ActionShortcuts {
            get {
                return ResourceManager.GetString("ActionShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type ähnelt.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Activate HDR ähnelt.
        /// </summary>
        public static string ActivateHDR {
            get {
                return ResourceManager.GetString("ActivateHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All displays ähnelt.
        /// </summary>
        public static string AllDisplays {
            get {
                return ResourceManager.GetString("AllDisplays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoActions is already running. ähnelt.
        /// </summary>
        public static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application closed actions ähnelt.
        /// </summary>
        public static string AppClosedActions {
            get {
                return ResourceManager.GetString("AppClosedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application got focus actions ähnelt.
        /// </summary>
        public static string AppFocusedActions {
            get {
                return ResourceManager.GetString("AppFocusedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application ähnelt.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application action ähnelt.
        /// </summary>
        public static string ApplicationAction {
            get {
                return ResourceManager.GetString("ApplicationAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application name ähnelt.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Applications ähnelt.
        /// </summary>
        public static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application lost focus actions ähnelt.
        /// </summary>
        public static string AppLostFocusActions {
            get {
                return ResourceManager.GetString("AppLostFocusActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application started actions ähnelt.
        /// </summary>
        public static string AppStartedActions {
            get {
                return ResourceManager.GetString("AppStartedActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arguments ähnelt.
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audio ähnelt.
        /// </summary>
        public static string AudioAction {
            get {
                return ResourceManager.GetString("AudioAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoActions ähnelt.
        /// </summary>
        public static string AutoActions {
            get {
                return ResourceManager.GetString("AutoActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enable HDR on this monitor, based on the applications ähnelt.
        /// </summary>
        public static string AutoActionsToolTip {
            get {
                return ResourceManager.GetString("AutoActionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto-Start ähnelt.
        /// </summary>
        public static string AutoStart {
            get {
                return ResourceManager.GetString("AutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update automatically ähnelt.
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap beer {
            get {
                object obj = ResourceManager.GetObject("beer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Buy me a beer! ähnelt.
        /// </summary>
        public static string BuyBeer {
            get {
                return ResourceManager.GetString("BuyBeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change color depth ähnelt.
        /// </summary>
        public static string ChangeColorDepth {
            get {
                return ResourceManager.GetString("ChangeColorDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change HDR ähnelt.
        /// </summary>
        public static string ChangeHDR {
            get {
                return ResourceManager.GetString("ChangeHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changelog ähnelt.
        /// </summary>
        public static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change playback device ähnelt.
        /// </summary>
        public static string ChangePlaybackDevice {
            get {
                return ResourceManager.GetString("ChangePlaybackDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change record device ähnelt.
        /// </summary>
        public static string ChangeRecordDevice {
            get {
                return ResourceManager.GetString("ChangeRecordDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change refresh rate ähnelt.
        /// </summary>
        public static string ChangeRefreshRate {
            get {
                return ResourceManager.GetString("ChangeRefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change resolution ähnelt.
        /// </summary>
        public static string ChangeResolution {
            get {
                return ResourceManager.GetString("ChangeResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for new version on startup ähnelt.
        /// </summary>
        public static string CheckForNewVersion {
            get {
                return ResourceManager.GetString("CheckForNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose application ähnelt.
        /// </summary>
        public static string ChooseApplication {
            get {
                return ResourceManager.GetString("ChooseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose UWP app... ähnelt.
        /// </summary>
        public static string ChooseUWPApplication {
            get {
                return ResourceManager.GetString("ChooseUWPApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close program ähnelt.
        /// </summary>
        public static string CloseProgramAction {
            get {
                return ResourceManager.GetString("CloseProgramAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Color depth [bit] ähnelt.
        /// </summary>
        public static string ColorDepth {
            get {
                return ResourceManager.GetString("ColorDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 10-Bit ähnelt.
        /// </summary>
        public static string ColorDepth_BPC10 {
            get {
                return ResourceManager.GetString("ColorDepth.BPC10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 12-Bit ähnelt.
        /// </summary>
        public static string ColorDepth_BPC12 {
            get {
                return ResourceManager.GetString("ColorDepth.BPC12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 16-Bit ähnelt.
        /// </summary>
        public static string ColorDepth_BPC16 {
            get {
                return ResourceManager.GetString("ColorDepth.BPC16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 6-Bit ähnelt.
        /// </summary>
        public static string ColorDepth_BPC6 {
            get {
                return ResourceManager.GetString("ColorDepth.BPC6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 8-Bit ähnelt.
        /// </summary>
        public static string ColorDepth_BPC8 {
            get {
                return ResourceManager.GetString("ColorDepth.BPC8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - ähnelt.
        /// </summary>
        public static string ColorDepth_BPCUnkown {
            get {
                return ResourceManager.GetString("ColorDepth.BPCUnkown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restarts the application on first occurence, as the application may need HDR to be activated before launching it. ähnelt.
        /// </summary>
        public static string CompatibilityModeToolTip {
            get {
                return ResourceManager.GetString("CompatibilityModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create logfile ähnelt.
        /// </summary>
        public static string CreateLogFile {
            get {
                return ResourceManager.GetString("CreateLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current application ähnelt.
        /// </summary>
        public static string CurrentApplication {
            get {
                return ResourceManager.GetString("CurrentApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current profile: ähnelt.
        /// </summary>
        public static string CurrentProfile {
            get {
                return ResourceManager.GetString("CurrentProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deactivate HDR ähnelt.
        /// </summary>
        public static string DeactivateHDR {
            get {
                return ResourceManager.GetString("DeactivateHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default profile ähnelt.
        /// </summary>
        public static string DefaultProfile {
            get {
                return ResourceManager.GetString("DefaultProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device ID ähnelt.
        /// </summary>
        public static string DeviceID {
            get {
                return ResourceManager.GetString("DeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UID ähnelt.
        /// </summary>
        public static string DeviceUID {
            get {
                return ResourceManager.GetString("DeviceUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display ähnelt.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display action ähnelt.
        /// </summary>
        public static string DisplayAction {
            get {
                return ResourceManager.GetString("DisplayAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display name ähnelt.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays ähnelt.
        /// </summary>
        public static string Displays {
            get {
                return ResourceManager.GetString("Displays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download from GitHub ähnelt.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string DownloadNewestVersion {
            get {
                return ResourceManager.GetString("DownloadNewestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to restart application. ähnelt.
        /// </summary>
        public static string ExceptionRestartProcess {
            get {
                return ResourceManager.GetString("ExceptionRestartProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File path ähnelt.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Force closing ähnelt.
        /// </summary>
        public static string ForceKill {
            get {
                return ResourceManager.GetString("ForceKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GitHub ähnelt.
        /// </summary>
        public static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use automated HDR Mode for all monitors ähnelt.
        /// </summary>
        public static string GlobalAutoHDR {
            get {
                return ResourceManager.GetString("GlobalAutoHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics card ähnelt.
        /// </summary>
        public static string GraphicsCard {
            get {
                return ResourceManager.GetString("GraphicsCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HDR ähnelt.
        /// </summary>
        public static string HDR {
            get {
                return ResourceManager.GetString("HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto HDR Mode ähnelt.
        /// </summary>
        public static string HDRMode {
            get {
                return ResourceManager.GetString("HDRMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide splash screen on startup ähnelt.
        /// </summary>
        public static string HideSplashScreenOnStartup {
            get {
                return ResourceManager.GetString("HideSplashScreenOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide splash screen on update ähnelt.
        /// </summary>
        public static string HideSplashScreenOnUpdate {
            get {
                return ResourceManager.GetString("HideSplashScreenOnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Icon ähnelt.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Info ähnelt.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary ähnelt.
        /// </summary>
        public static string IsPrimaryMonitor {
            get {
                return ResourceManager.GetString("IsPrimaryMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last actions ähnelt.
        /// </summary>
        public static string LastActions {
            get {
                return ResourceManager.GetString("LastActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Launch application ähnelt.
        /// </summary>
        public static string LaunchApplication {
            get {
                return ResourceManager.GetString("LaunchApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die License ähnelt.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GNU GENERAL PUBLIC LICENSE
        ///                       Version 3, 29 June 2007
        ///
        /// Copyright (C) 2007 Free Software Foundation, Inc. &lt;http://fsf.org/&gt;
        /// Everyone is permitted to copy and distribute verbatim copies
        /// of this license document, but changing it is not allowed.
        ///
        ///                            Preamble
        ///
        ///  The GNU General Public License is a free, copyleft license for
        ///software and other kinds of works.
        ///
        ///  The licenses for most software and other practical works are designed
        ///to take away your free [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        public static string LicenseContent {
            get {
                return ResourceManager.GetString("LicenseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local ähnelt.
        /// </summary>
        public static string Local {
            get {
                return ResourceManager.GetString("Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging ähnelt.
        /// </summary>
        public static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logs ähnelt.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        public static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automated HDR mode ähnelt.
        /// </summary>
        public static string ManagedHDR {
            get {
                return ResourceManager.GetString("ManagedHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid settings. ähnelt.
        /// </summary>
        public static string MessageInvalidSettings {
            get {
                return ResourceManager.GetString("MessageInvalidSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mssing audio device. ähnelt.
        /// </summary>
        public static string MessageMissingAudioDevice {
            get {
                return ResourceManager.GetString("MessageMissingAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing file. ähnelt.
        /// </summary>
        public static string MessageMissingFile {
            get {
                return ResourceManager.GetString("MessageMissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing process name. ähnelt.
        /// </summary>
        public static string MessageMissingProcessName {
            get {
                return ResourceManager.GetString("MessageMissingProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refrenced profile is creating a loop. ähnelt.
        /// </summary>
        public static string MessageReferenceLoop {
            get {
                return ResourceManager.GetString("MessageReferenceLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Referenced profile with Guid {0} hasn&apos;t been found. ähnelt.
        /// </summary>
        public static string MessageReferenceProfileNotFound {
            get {
                return ResourceManager.GetString("MessageReferenceProfileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close to tray ähnelt.
        /// </summary>
        public static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displays ähnelt.
        /// </summary>
        public static string Monitors {
            get {
                return ResourceManager.GetString("Monitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No application is running ähnelt.
        /// </summary>
        public static string NoApplication {
            get {
                return ResourceManager.GetString("NoApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No profile assigned ähnelt.
        /// </summary>
        public static string NoProfile {
            get {
                return ResourceManager.GetString("NoProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online ähnelt.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Priority ähnelt.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Process name ähnelt.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profiles ähnelt.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference profile ähnelt.
        /// </summary>
        public static string ReferenceProfileAction {
            get {
                return ResourceManager.GetString("ReferenceProfileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh rate [Hz] ähnelt.
        /// </summary>
        public static string RefreshRate {
            get {
                return ResourceManager.GetString("RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Release date ähnelt.
        /// </summary>
        public static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string RemoveApplication {
            get {
                return ResourceManager.GetString("RemoveApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string RemoveProfile {
            get {
                return ResourceManager.GetString("RemoveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Resolution ähnelt.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart app ähnelt.
        /// </summary>
        public static string RestartProccessOnFirstOccurence {
            get {
                return ResourceManager.GetString("RestartProccessOnFirstOccurence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run ähnelt.
        /// </summary>
        public static string RunAction {
            get {
                return ResourceManager.GetString("RunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Run program ähnelt.
        /// </summary>
        public static string RunProgramAction {
            get {
                return ResourceManager.GetString("RunProgramAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit application ähnelt.
        /// </summary>
        public static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SplashScreen {
            get {
                object obj = ResourceManager.GetObject("SplashScreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start to tray ähnelt.
        /// </summary>
        public static string StartToTray {
            get {
                return ResourceManager.GetString("StartToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating AutoActions... ähnelt.
        /// </summary>
        public static string Updating {
            get {
                return ResourceManager.GetString("Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Version ähnelt.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume sync devices ähnelt.
        /// </summary>
        public static string VolumeSyncDevices {
            get {
                return ResourceManager.GetString("VolumeSyncDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wait for program to exit ähnelt.
        /// </summary>
        public static string WaitForProgramEnd {
            get {
                return ResourceManager.GetString("WaitForProgramEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        // ---- Microphone monitoring (added by hand: MSBuild does not run PublicResXFileCodeGenerator) ----

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Microphone monitoring ähnelt.
        /// </summary>
        public static string MicMonitoring {
            get {
                return ResourceManager.GetString("MicMonitoring", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playback device ähnelt.
        /// </summary>
        public static string MicMonitoringDevice {
            get {
                return ResourceManager.GetString("MicMonitoringDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input line ähnelt.
        /// </summary>
        public static string MicMonitoringLine {
            get {
                return ResourceManager.GetString("MicMonitoringLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Default playback device ähnelt.
        /// </summary>
        public static string MicMonitoringDefaultDevice {
            get {
                return ResourceManager.GetString("MicMonitoringDefaultDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitoring ähnelt.
        /// </summary>
        public static string MicMonitoringEnable {
            get {
                return ResourceManager.GetString("MicMonitoringEnable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitoring volume ähnelt.
        /// </summary>
        public static string MicMonitoringVolume {
            get {
                return ResourceManager.GetString("MicMonitoringVolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No controllable input line on the selected playback device ähnelt.
        /// </summary>
        public static string MicMonitoringUnavailable {
            get {
                return ResourceManager.GetString("MicMonitoringUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The playback device and input line are chosen in Settings. ähnelt.
        /// </summary>
        public static string MicMonitoringSettingsHint {
            get {
                return ResourceManager.GetString("MicMonitoringSettingsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select at least one of: monitoring, monitoring volume ähnelt.
        /// </summary>
        public static string MessageMissingMicMonitoringSetting {
            get {
                return ResourceManager.GetString("MessageMissingMicMonitoringSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Appearance ähnelt.
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Theme ähnelt.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Follow Windows ähnelt.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light ähnelt.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dark ähnelt.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A personal fork of AutoActions by Codectory ... ähnelt.
        /// </summary>
        public static string AboutBasedOn {
            get {
                return ResourceManager.GetString("AboutBasedOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original project ähnelt.
        /// </summary>
        public static string UpstreamProject {
            get {
                return ResourceManager.GetString("UpstreamProject", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This fork ähnelt.
        /// </summary>
        public static string ForkRepository {
            get {
                return ResourceManager.GetString("ForkRepository", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display colour ähnelt.
        /// </summary>
        public static string DisplayColorAction {
            get {
                return ResourceManager.GetString("DisplayColorAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital vibrance ähnelt.
        /// </summary>
        public static string DisplayColorVibrance {
            get {
                return ResourceManager.GetString("DisplayColorVibrance", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hue ähnelt.
        /// </summary>
        public static string DisplayColorHue {
            get {
                return ResourceManager.GetString("DisplayColorHue", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brightness ähnelt.
        /// </summary>
        public static string DisplayColorBrightness {
            get {
                return ResourceManager.GetString("DisplayColorBrightness", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contrast ähnelt.
        /// </summary>
        public static string DisplayColorContrast {
            get {
                return ResourceManager.GetString("DisplayColorContrast", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gamma ähnelt.
        /// </summary>
        public static string DisplayColorGamma {
            get {
                return ResourceManager.GetString("DisplayColorGamma", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Digital vibrance and hue need an NVIDIA GPU. Brightness, contrast a... ähnelt.
        /// </summary>
        public static string DisplayColorNvidiaOnlyHint {
            get {
                return ResourceManager.GetString("DisplayColorNvidiaOnlyHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exclusive-fullscreen games overwrite the gamma ramp when they launc... ähnelt.
        /// </summary>
        public static string DisplayColorFullscreenHint {
            get {
                return ResourceManager.GetString("DisplayColorFullscreenHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows checks every gamma ramp and refuses one that strays too f... ähnelt.
        /// </summary>
        public static string DisplayColorGammaRangeWarning {
            get {
                return ResourceManager.GetString("DisplayColorGammaRangeWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unlock the full gamma range... ähnelt.
        /// </summary>
        public static string DisplayColorUnlockGammaRange {
            get {
                return ResourceManager.GetString("DisplayColorUnlockGammaRange", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Some colour settings could not be applied. ähnelt.
        /// </summary>
        public static string DisplayColorPartlyUnavailable {
            get {
                return ResourceManager.GetString("DisplayColorPartlyUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose at least one colour setting to change. ähnelt.
        /// </summary>
        public static string MessageMissingDisplayColorSetting {
            get {
                return ResourceManager.GetString("MessageMissingDisplayColorSetting", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quick settings ähnelt.
        /// </summary>
        public static string QuickSettings {
            get {
                return ResourceManager.GetString("QuickSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset colour ähnelt.
        /// </summary>
        public static string QuickSettingsResetColor {
            get {
                return ResourceManager.GetString("QuickSettingsResetColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vibrance and hue are read from the driver. Brightness, contrast and... ähnelt.
        /// </summary>
        public static string QuickSettingsColorHint {
            get {
                return ResourceManager.GetString("QuickSettingsColorHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes here apply immediately and are not saved. A profile action ... ähnelt.
        /// </summary>
        public static string QuickSettingsHint {
            get {
                return ResourceManager.GetString("QuickSettingsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HDR per display is on the Displays page. Resolution, refresh rate a... ähnelt.
        /// </summary>
        public static string QuickSettingsDisplayModeHint {
            get {
                return ResourceManager.GetString("QuickSettingsDisplayModeHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Playback device ähnelt.
        /// </summary>
        public static string PlaybackDevice {
            get {
                return ResourceManager.GetString("PlaybackDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recording device ähnelt.
        /// </summary>
        public static string RecordDevice {
            get {
                return ResourceManager.GetString("RecordDevice", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets ähnelt.
        /// </summary>
        public static string QuickSettingsPresets {
            get {
                return ResourceManager.GetString("QuickSettingsPresets", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save as preset ähnelt.
        /// </summary>
        public static string QuickSettingsSavePreset {
            get {
                return ResourceManager.GetString("QuickSettingsSavePreset", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preset name ähnelt.
        /// </summary>
        public static string QuickSettingsPresetName {
            get {
                return ResourceManager.GetString("QuickSettingsPresetName", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A preset is an action shortcut, so it also appears on the Status pa... ähnelt.
        /// </summary>
        public static string QuickSettingsPresetsHint {
            get {
                return ResourceManager.GetString("QuickSettingsPresetsHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply ähnelt.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hotkey ähnelt.
        /// </summary>
        public static string Hotkey {
            get {
                return ResourceManager.GetString("Hotkey", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click and press a combination with Ctrl, Alt, Shift or Win. Backspa... ähnelt.
        /// </summary>
        public static string HotkeyHint {
            get {
                return ResourceManager.GetString("HotkeyHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows refused this combination, probably because another program ... ähnelt.
        /// </summary>
        public static string HotkeyUnavailable {
            get {
                return ResourceManager.GetString("HotkeyUnavailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die None ähnelt.
        /// </summary>
        public static string HotkeyNone {
            get {
                return ResourceManager.GetString("HotkeyNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus delay (seconds) ähnelt.
        /// </summary>
        public static string FocusDebounce {
            get {
                return ResourceManager.GetString("FocusDebounce", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die How long a window has to keep or lose focus before Got focus and Lo... ähnelt.
        /// </summary>
        public static string FocusDebounceHint {
            get {
                return ResourceManager.GetString("FocusDebounceHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Re-apply colour settings automatically ähnelt.
        /// </summary>
        public static string ReapplyDisplayColor {
            get {
                return ResourceManager.GetString("ReapplyDisplayColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Windows clears the gamma ramp on a display mode change, on resume f... ähnelt.
        /// </summary>
        public static string ReapplyDisplayColorHint {
            get {
                return ResourceManager.GetString("ReapplyDisplayColorHint", resourceCulture);
            }
        }

        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Behaviour ähnelt.
        /// </summary>
        public static string Behaviour {
            get {
                return ResourceManager.GetString("Behaviour", resourceCulture);
            }
        }
    }
}
